# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy Docker Image to Azure VM

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/vehicleproj:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/vehicleproj:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull and run Docker image on Azure VM
        run: |
          az login --identity  # only if using managed identity on VM
          az acr login --name ${{ secrets.ACR_NAME }}  # required for private ACR

          docker pull ${{ secrets.ACR_LOGIN_SERVER }}/vehicleproj:latest
          docker run -d \
            -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
            -p 5000:5000 \
            ${{ secrets.ACR_LOGIN_SERVER }}/vehicleproj:latest

